### PR TITLE
Add undesired-visitor-plugin to the plugins list

### PR DESCRIPTION
**Pull request by NullIsNot0**
Undesired Visitor Plugin's purpose is to block bad bots by their User-Agent header value. Bad bots list is read by Christian's script from reputable lists. 

Plugin uses rule IDs 9,523,000 - 9,523,999, but this can be changed, if necessary.

I use this plugin in production, so it's considered tested.

### CODE REVIEW

**Comment by theseion** [comment]
Thanks a log @NullIsNot0!

For us, "tested" also means that it needs to have test coverage. You can see how that is done in the [Nextcloud plugin](https://github.com/coreruleset/nextcloud-rule-exclusions-plugin), for example. It would be great if you could add a couple of base tests at least.

**Comment by dune73** [comment]
Thank you for creating a plugin with all this data.

2 cents:
* I think the name "undesired-visitors" is not very telling. Can you replace this with something that expresses what the plugin is actually doing / detecting
* The README could do with an explanation how you generate the list.
* If you generate the list based on my script, then please explain this
* I suggest to move the all-in-one.sh script into a bin folder
* You may want to comment and consolidate the script a bit. I know I sent you a raw version, but I did not mean it to be published as is, more as a reference or a source for your work

**Comment by NullIsNot0** [comment]
Thank you for suggestions! I see, the plugin needs to be renamed and better documented. I'll close this PR for now and return with a new PR when I have done things you mentioned.

**Comment by dune73** [comment]
Very good plan. And looking forward to this.

**Pull request closed without merging**
