### PR TITLE
phpBB plugin - exclusions

### PR DESCRIPTION
**Pull request by azurit**
Not sure if name phpBB is sufficient - maybe we should have some format for naming exclusion plugins? Like 'phpBB exclusions'.

### CODE REVIEW

**Comment by dune73** [comment]
I've been thinking about this as well.

We can prefix, so the RE plugins are show up in the same alphabetical order. Or we suffix, then they are ordered by the software they address.

Anyway, I think the name ought make a reference to rule exclusions. Which variant do you prefer?

Also: Might have to rename the google oauth2 plugin too.

**Comment by azurit** [comment]
I would not go with prefixes as it will make plugin harder to find (imagine that in, for example, 1 year we will have 50 plugins). Maybe creating a separate table for exclusion plugins?

**Comment by azurit** [comment]
> Also: Might have to rename the google oauth2 plugin too.

Didn't realize that this one is exclusion package too. :)

**Comment by dune73** [comment]
Separate table would make sense. As might separated rule range. But I do not really know how things would develop so allocating a separate rule range could lead us into dead end.

However, cunning idea: We wave rule range 9,500,000-9,899,000 (above is incubator). So what we could do is enumerate standard plugins from 9,500,000 upwards and RE plugins from 9,899,000 downwards.

**Comment by azurit** [comment]
Sorry for late reaction!

> However, cunning idea: We wave rule range 9,500,000-9,899,000 (above is incubator). So what we could do is enumerate standard plugins from 9,500,000 upwards and RE plugins from 9,899,000 downwards.

Is and will be the plugins table sorted by ID range?

**Comment by azurit** [comment]
Closing in favor of https://github.com/coreruleset/plugin-registry/pull/8.

**Pull request closed without merging**
