### PR TITLE
Body decompress plugin registration

### PR DESCRIPTION
**Pull request by azurit**
Body decompress plugin registration request.

### CODE REVIEW

**Comment by dune73** [comment]
Here is your repo: https://github.com/coreruleset/body-decompress-plugin

Looking fwd to this very much!

**Comment by azurit** [comment]
Dear reviewers (@dune73 @airween @fzipi), documentation was updated:
 - added information about embedded vs. proxy mode
 - added Testing section

Thank you!

**Comment by dune73** [comment]
There is still a disagreement between @lifeforms and myself with regards to plugin activation. We really ought to talk this through.

@airween and @fzipi : Did you find time to review this?

**Comment by airween** [comment]
Not yet, last few weeks was very busy. Hope that I can do that soon.

**Comment by azurit** [comment]
Is it possible to merge this? Thank you.

**Comment by dune73** [comment]
You are right. Good you are speaking up. @lifeforms and I have sorted our differences when it comes to plugin activation. We just never communicated how it is meant to be done. It also means a chance to your plugin. Are you available for a chat on the subject tomorrow? I'd like to explain our reasoning after keeping you back for so long.

**Comment by dune73** [comment]
I'm merging this now and we will fix activation in the plugin. This has been open much too long and it's my fault.

**Pull request merged**
