### PR TITLE
Antivirus plugin registration

### PR DESCRIPTION
**Pull request by azurit**
Antivirus plugin registration.

### CODE REVIEW

**Comment by dune73** [comment]
Thanks. Happy to merge when the plugin is done implementing.

**Comment by azurit** [comment]
How am i suppose to start it when i don't have access into repo for antivirus plugin? I probably don't understand the sequence of adding new plugin.

**Comment by dune73** [comment]
Well, we better set up such a process then. :)

I definitely see your problem.

**Comment by azurit** [comment]
Everything should be ready for this to be merged!

**Comment by dune73** [comment]
Plugin works like a charm.

**Pull request merged**
