### PR TITLE
Tested plugins

### PR DESCRIPTION
**Pull request by azurit**
phpMyAdmin and Nextcloud plugins are tested.

### CODE REVIEW

**Comment by dune73** [comment]
There was a testing methodology proposed / defined for plugins by @fzipi. Did you follow that? (do not have the link handy).

**Comment by azurit** [comment]
Oh, no, didn't know about that. But both plugins are used in production:
 - phpMyAdmin by hundreds of my users
 - Nextcloud by lot of our users based on number of issues and PRs which we are receiving

@fzipi Can you share a link? Thanks.

**Comment by EsadCetiner** [comment]
@azurit The Nextcloud plugin has improved significantly last year, but it still has a lot more work to do. The plugin has no support for Nextcloud Office and Nextcloud Talk which are installed out of the box. maybe change it to being tested instead of tested since I do plan to open a PR to add support for Nextcloud Office at some point.

**Comment by azurit** [comment]
@EsadCetiner Tested doesn't mean it is resolving all possible FPs. We don't need to support the whole application to consider plugin as tested (this will, probably, never happen). Let's see what @fzipi has.

**Comment by dune73** [comment]
FYI: @fzipi is on holiday for a couple of days. So do not expect a response very fast.

**Comment by azurit** [comment]
@fzipi Ping.

**Comment by azurit** [comment]
@theseion Do you know anything about testing methodology for plugins?

**Comment by fzipi** [comment]
@azurit See https://github.com/coreruleset/template-plugin?tab=readme-ov-file#testing. And also there is an example and in general that template structure https://github.com/coreruleset/template-plugin.

Tests are simple: just copy the `.github/workflows` folder to your plugin, and write tests with the structure you want to test. See the example [here](https://github.com/coreruleset/template-plugin/blob/main/tests/regression/template-plugin/9500100.yaml)

**Comment by dune73** [comment]
@azurit can you do this for the fake plugin asap?

**Comment by azurit** [comment]
@dune73 Yes.

**Comment by azurit** [comment]
@dune73  @fzipi Any hints?
https://github.com/coreruleset/fake-bot-plugin/actions/runs/7904772759/job/21575948403

**Comment by dune73** [comment]
Not me, sorry.

**Comment by azurit** [comment]
Rechecked it and i don't see any error on my side (but i'm not an expert on out test framework). @theseion Maybe you can take a look at it pls?

**Comment by azurit** [comment]
Got it!

@dune73 My tests are failing and i don't see why - plugin needs an access to the internet and working DNS resolving to work. Are those available in testing environment?

**Comment by azurit** [comment]
Also, it needs LuaSocket library.

**Comment by theseion** [comment]
Looks like you've got it handle @azurit, otherwise ping me.

**Comment by dune73** [comment]
So the fake-bot-plugin is now tested and we can do a separate PR? Please confirm, I'd like to list it as tested ASAP.

**Comment by theseion** [comment]
No, the tests are still failing (I guess due to a missing Lua library).

**Pull request closed without merging**
